### ISSUE TITLE
Cannot find module doc-parser

### ISSUE THREAD

**Issue by zertex** [glayzzle/doc-parser#2]
I have error: Error: Cannot find module 'doc-parser'
Why?

P.S.
In html header: 
`<script src="vendor/npm-asset/doc-parser/dist/doc-parser.min.js"></script>`

Code:
`var DocParser = require('doc-parser');
    var reader = new DocParser({
       ...
    });
    var data = reader.parse(text);
    console.log(data);`

**Comment by ichiriac** [comment]
should work, it's packed with browserify.

Can you provide a sample code with codepen, it's maybe conflicting with another `require` module

**Comment by ichiriac** [comment]
sorry, I've used the wrong alias - it's fixed and will be released soon
